-- -- Conversations
-- CREATE TABLE conversations (
--     id SERIAL PRIMARY KEY,
--     created_at TIMESTAMP DEFAULT NOW(),
--     updated_at TIMESTAMP DEFAULT NOW()
-- );

-- --  Participants in each conversation
-- CREATE TABLE conversation_participants (
--     id SERIAL PRIMARY KEY,
--     conversation_id INT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
--     user_id INT NOT NULL REFERENCES "Users"(id) ON DELETE CASCADE,
--     blacklist BOOLEAN DEFAULT FALSE,
--     favorite_list BOOLEAN DEFAULT FALSE
-- );

-- --  Messages inside a conversation
-- CREATE TABLE messages (
--     id SERIAL PRIMARY KEY,
--     body TEXT NOT NULL,
--     conversation_id INT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
--     sender_id INT NOT NULL REFERENCES "Users"(id) ON DELETE CASCADE,
--     created_at TIMESTAMP DEFAULT NOW(),
--     updated_at TIMESTAMP DEFAULT NOW()
-- );

-- --  Catalogs 
-- CREATE TABLE catalogs (
--     id SERIAL PRIMARY KEY,
--     user_id INT NOT NULL REFERENCES "Users"(id) ON DELETE CASCADE,
--     catalog_name VARCHAR(255) NOT NULL,
--     created_at TIMESTAMP DEFAULT NOW(),
--     updated_at TIMESTAMP DEFAULT NOW()
-- );

-- --  Сatalog-conversations
-- CREATE TABLE catalog_conversations (
--     catalog_id INT NOT NULL REFERENCES catalogs(id) ON DELETE CASCADE,
--     conversation_id INT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
--     PRIMARY KEY (catalog_id, conversation_id)
-- );
